import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

import localFont from "next/font/local";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

// Font files can be collocated inside of `pages`
const myFont = localFont({ src: "./assets/go3v2.ttf" });

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex ">{children}</main>
        <footer className="p-4 bg-black">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
