import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import localFont from "next/font/local";
import Footer from "@/components/Footer";
import { RecipesProvider } from "@/context/RecipesContext";

// Font files can be collocated inside of `pages`
const myFont = localFont({ src: "./assets/go3v2.ttf" });

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RecipesProvider>
          <main className=" min-h-screen bg-gradient-to-t from-cyan-100 to-cyan-50">{children}</main>
        </RecipesProvider>
        <footer className="p-4 bg-black">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
